set x=createobject("wscript.shell")
x.run"notepad.exe"
wscript.sleep 2000
x.sendkeys"set x=createobject(wscript.shell)"
x.sendkeys"{enter}"
x.sendkeys"x.runnotepad.exe"
x.sendkeys"{enter}"
x.sendkeys"wscript.sleep 2000"
x.sendkeys"{enter}"
x.sendkeys"x.sendkeyshi hi hi"
x.sendkeys"{enter}"
x.sendkeys"x.sendkeyss"
x.sendkeys"wscript.sleep 500"
x.sendkeys"{enter}"
x.sendkeys"x.sendkeysjkfdds.vbs"
x.sendkeys"{enter}"
x.sendkeys"x.sendkeys{enter}"
x.sendkeys"^s"
wscript.sleep 500
x.sendkeys"jkfd.vbs"
x.sendkeys"{enter}"