services:
    mustache:
        image: python
        volumes:
            - ./src:/app/src
            - ./build:/app/build
            - ./build.py:/app/build.py
        working_dir: /app
        entrypoint: ["./build.py", "--watch", "asd"]
