@startuml

rectangle "Alerting System"
rectangle "Logging System"
"Logging System" -> "Alerting System" : something failed!

rectangle "Git Server" {
}

rectangle "Job Scheduler" {
}
"Job Scheduler" -> "CI Server" : laminarc queue $job

rectangle "CI Server" {
}
"CI Server" -> "Build System" : trigger build
"CI Server" <- "Build System" : build logs, exit code
"CI Server" -> "Logging System" : ci job failed!

rectangle "Healthcheck System"
"Healthcheck System" -> "CI Server" : has there been a recent success?

rectangle "Artifact Repository" {
}

rectangle "Build System" {
    database Secrets

    node "Build Environment"
    "Build Environment" <- Secrets
    "Build Environment" -> "Artifact Repository" : build artifacts

    /'
    cloud "Cloud Services" {
        cloud "GitHub Actions"
        cloud "GitLab Runners"
        cloud "sr.ht"
        cloud "codeberg"
    }
    rectangle "Hosted Software" {
        database Jenkins
        database GitLaba
    }'/
}
"Build System" <- "Git Server" : git clone $job

cloud Internet {
    actor User
    User <- "Git Server" : https://git.griffinht.com
    User <- "Artifact Repository" : wget https://artifacts.griffinht.com/software/version.tar.gz
}

cloud "Internal Network" {
    actor Developer
    Developer -> "Git Server" : git://git.griffinht.com/$repository
    Developer -> "Build System" : laminarc queue $job
    Developer <- "Alerting System" : email developer@griffinht.com
}

@enduml
