[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=0
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=install fake virus?
DisplayLicense=
FinishMessage=done installing fake virus
TargetName=C:\Users\griffin\Desktop\My Files\Coding\Hackersss\fakevirus\installfakevirus.EXE
FriendlyName=fake virus
AppLaunched=start.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="fakevirus.vbs"
FILE1="shutdown.bat"
FILE2="shutdownlnk.bat"
FILE3="start.bat"
[SourceFiles]
SourceFiles0=C:\Users\griffin\Desktop\My Files\Coding\Hackersss\fakevirus\fakevirus\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
