apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
spec:
  accessModes:
    # read/write from a single node
    # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    - ReadWriteOnce
  # todo idk where the docs are for this - i just guessed
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
    name: caddy
spec:
    containers:
      - name: caddy
        image: caddy/caddy
      - name: tailscale
        image: ghcr.io/tailscale/tailscale:latest
        env:
          # disable Kubernetes secrets and use OAuth login instead
          - name: TS_KUBE_SECRET
            value: ""
          - name: TS_STATE_DIR
            value: "/var/lib/tailscale"
        volumeMounts:
          - name: tailscale-state
            mountPath: "/var/lib/tailscale"
    volumes:
      - name: tailscale-state
        persistentVolumeClaim:
          claimName: tailscale-state
