@startuml

database git [
    git
    ===
    griffinht.com
    hot
    other
]

node nginx {
    node "git-send-pack(1)"
    "git-send-pack(1)" <- git
    "git-send-pack(1)" <- nginx : cgi

    node cgit
    cgit <- git
    cgit <- nginx : cgi
}

node "git-daemon(1)" {
    rectangle "git-receive-pack(1)" -> git
}

@enduml
