services:
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      #- TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_USERSPACE=false
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
