apiVersion: v1
kind: Pod
metadata:
    name: tailscale
spec:
    containers:
      - name: tailscale
        image: ghcr.io/tailscale/tailscale:latest
        env:
          # disable Kubernetes secrets and use OAuth login instead
          - name: TS_KUBE_SECRET
            value: ""
          - name: TS_USERSPACE
            value: "false"
          - name: TS_DEST_IP
            value: "10.96.0.0/16"
        volumeMounts:
          - name: tun-device
            mountPath: /dev/net/tun
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    volumes:
      - name: tun-device
        hostPath:
          path: /dev/net/tun
