apiVersion: v1
kind: Service
metadata:
    name: caddy-service
spec:
    selector:
        app: caddy
    ports:
      - protocol: TCP
        port: 80
---
apiVersion: v1
kind: Service
metadata:
    name: iperf-service
spec:
    selector:
        app: iperf3
    ports:
      - protocol: TCP
        port: 5201
        # todo does iperf also need UDP?
---
